### ISSUE TITLE
Module info page is down

### ISSUE THREAD

**Issue by hongshaoyang** [nusmodifications/nusmods-api#15]
hi kind admins,

i didn't know where else to contact so i just went straight here, hope you guys don't mind. i think this is a new issue (?), but when i try to navigate to the information page of any module it redirects back to the timetable page.

**Comment by yangshun** [comment]
Possibly related to https://github.com/nusmodifications/nusmods/pull/292

**Comment by yangshun** [comment]
Thanks for the report. Fixed in https://github.com/nusmodifications/nusmods/commit/742033830af754aff7f763b67f6d0371cd46231c
