### ISSUE TITLE
strip &nbsp; in text

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods-api#20]
e.g. http://api.nusmods.com/2016-2017/modules/EN2202.json you'll see "WeekText":"EveryÂ Week", due to a &nbsp in the html page 
https://myaces.nus.edu.sg/cors/jsp/report/ModuleDetailedInfo.jsp?acad_y=2016/2017&sem_c=2&mod_c=EN2202

**Comment by li-kai** [comment]
Fixed in #22
