### ISSUE TITLE
[Feature] Including CORS Bidding Activity

### ISSUE THREAD

**Issue by yeesian** [nusmodifications/nusmods-api#3]
Fetch the data pertaining to each individual bid from the [Global Bidding Activity History Information Listing](https://sit.aces01.nus.edu.sg/cors/jsp/report/GlobalBidHistDetails.jsp) (**warning**: the link might change from sem to sem)

The HTML tables ([example here](https://sit.aces01.nus.edu.sg/cors/jsp/report/GlobalBidHistDetails.jsp?MOD_C=ACC1002X&ROUND_N=1C)) aren't straightforward to parse; you might find [an earlier effort](https://github.com/yeesian/NUS-Bidding-History) helpful

**Remarks**:
- The bidding activities for AY2013/2014 SEM 2 are not available, and
- the working link seems to point to the bidding activities for AY2013/AY2014 SEM 1 instead
- The [current link](https://myaces.nus.edu.sg/cors/jsp/report/GlobalBidHist.jsp) (hidden in the [CORS website](http://www.nus.edu.sg/cors/useful-info.html)) is not up yet

This data will be helpful in generating the charts for ahbeng/NUSMods#76

**Comment by yangshun** [comment]
CORS have closed these data, I'm afraid this is no longer relevant :(
