### ISSUE TITLE
AY17/18 semester 2 timetable data

### ISSUE THREAD

**Issue by irvinlim** [nusmodifications/nusmods-api#36]
Just wanted to check if the timetable information for semester 2 is ready, as it seems that http://api.nusmods.com/2017-2018/2/timetable.json is currently still empty. As the next semester is coming, I think many students want to start planning their timetables for next semester :)

I'm unfamiliar with the current process of how and where the data is currently being scraped from, but if there's any way I could help prepare the scrapers or the data I would like to help!

**Comment by ZhangYiJiang** [comment]
We've just started to scrape data for Sem 2 (the data only became available a few days ago). If you notice any module timetables that are missing, please do comment here so we can reopen this.

**Comment by irvinlim** [comment]
Thanks for the info!
